'use strict';
require('dotenv').config();
const express = require('express');
const { createClient } = require('@supabase/supabase-js');
const multer = require('multer');
const crypto = require('node:crypto');

const app = express();
const PORT = Number(process.env.PORT || 4173);
const production = process.env.NODE_ENV === 'production';
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SECRET_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!SUPABASE_URL || !SUPABASE_KEY || !process.env.SESSION_SECRET || process.env.SESSION_SECRET.length < 32) {
  throw new Error('Set SUPABASE_URL, SUPABASE_SECRET_KEY (or SUPABASE_SERVICE_ROLE_KEY), and a SESSION_SECRET of at least 32 characters.');
}
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } });
const UUID = /^[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}$/i;
const appError = (message, status = 400) => Object.assign(new Error(message), { status });
async function checked(query) { const { data, error } = await query; if (error) throw error; return data; }
async function ready() { await checked(supabase.from('users').select('id').limit(1)); }

app.disable('x-powered-by');
app.set('trust proxy', 1);
app.use((req,res,next)=>{res.set({'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Cache-Control':'no-store','Content-Security-Policy':"default-src 'self'; img-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self' 'unsafe-inline'; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'"});const m=(req.headers.cookie||'').match(/(?:^|;\s*)pp_session=([^;]+)/);req.cookies={session:m?decodeURIComponent(m[1]):null};next()});
app.use(express.json({limit:'16kb'}));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:4*1024*1024,files:1,fields:20},fileFilter:(_req,file,cb)=>{const ok=['image/jpeg','image/png','image/webp','application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'].includes(file.mimetype);cb(ok?null:appError('Unsupported file type.'),ok)}});
const hash=x=>crypto.createHmac('sha256',process.env.SESSION_SECRET).update(x).digest('hex');
const clean=(s,max=120)=>typeof s==='string'?s.trim().replace(/[\u0000-\u001f\u007f]/g,'').slice(0,max):'';
const oneOf=(v,arr)=>arr.includes(v);
function cookie(res,value,maxAge){res.setHeader('Set-Cookie',`pp_session=${encodeURIComponent(value)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${Math.floor(maxAge/1000)}${production?'; Secure':''}`)}
function originGuard(req,res,next){const origin=req.get('origin'),forwarded=req.get('x-forwarded-host'),host=forwarded?forwarded.split(',')[0].trim():req.get('host');if(!origin)return res.status(403).json({error:'Request origin required.'});try{if(new URL(origin).host!==host)return res.status(403).json({error:'Request origin not allowed.'})}catch{return res.status(403).json({error:'Request origin not allowed.'})}next()}
function rateLimit({name='general',limit=120,windowMs=60_000}={}){return async(req,res,next)=>{try{const routeKey=req.path.replace(UUID,':id');const key=hash(`${name}:${req.ip}:${routeKey}`);const {data,error}=await supabase.rpc('consume_rate_limit',{p_key:key,p_limit:limit,p_window_seconds:Math.ceil(windowMs/1000)});if(error)throw error;if(data!==true)return res.status(429).json({error:'Too many requests. Please try again shortly.'});next()}catch(e){next(e)}}}
app.use((req,res,next)=>['POST','PUT','PATCH','DELETE'].includes(req.method)?originGuard(req,res,next):next());
app.param('id',(req,res,next,id)=>UUID.test(id)?next():res.status(400).json({error:'Invalid resource ID.'}));

async function findUserByToken(token){if(!token)return null;const session=await checked(supabase.from('sessions').select('user_id').eq('token_hash',hash(token)).gt('expires_at',new Date().toISOString()).maybeSingle());if(!session)return null;return checked(supabase.from('users').select('id,nickname,branch,year,semester').eq('id',session.user_id).maybeSingle())}
async function auth(req,res,next){try{req.user=await findUserByToken(req.cookies.session);if(!req.user)return res.status(401).json({error:'Please sign in first.'});next()}catch(e){next(e)}}
async function optionalAuth(req,_res,next){try{req.user=await findUserByToken(req.cookies.session);next()}catch(e){next(e)}}
async function passwordHash(password,salt=crypto.randomBytes(16).toString('hex')){const key=await new Promise((resolve,reject)=>crypto.scrypt(password,salt,64,(err,out)=>err?reject(err):resolve(out)));return `${salt}:${key.toString('hex')}`}
async function passwordMatches(password,stored){const [salt,hex]=String(stored).split(':');if(!salt||!hex)return false;const key=await new Promise((resolve,reject)=>crypto.scrypt(password,salt,64,(err,out)=>err?reject(err):resolve(out)));const expected=Buffer.from(hex,'hex');return expected.length===key.length&&crypto.timingSafeEqual(expected,key)}
async function issueSession(userId,res){const token=crypto.randomBytes(32).toString('base64url');await checked(supabase.from('sessions').insert({token_hash:hash(token),user_id:userId,expires_at:new Date(Date.now()+7*86400_000).toISOString()}));cookie(res,token,7*86400_000)}
async function createNotification(userId,message){return checked(supabase.from('notifications').insert({id:crypto.randomUUID(),user_id:userId,message:clean(message,220)}))}

app.use('/api',rateLimit());
app.post('/api/register',rateLimit({name:'register',limit:8,windowMs:15*60_000}),async(req,res,next)=>{try{const nickname=clean(req.body.nickname,32),key=nickname.toLocaleLowerCase('en-US'),branch=clean(req.body.branch,60),year=clean(req.body.year,30),semester=clean(req.body.semester,30),password=req.body.password;if(!/^[\p{L}\p{N} _.-]{2,32}$/u.test(nickname)||!branch||!year||!semester||typeof password!=='string'||password.length<10||password.length>128)return res.status(400).json({error:'Use a 2–32 character nickname, complete your profile, and choose a password of at least 10 characters.'});const user={id:crypto.randomUUID(),nickname,nickname_key:key,password_hash:await passwordHash(password),branch,year,semester};await checked(supabase.from('users').insert(user));await issueSession(user.id,res);res.status(201).json({user:{id:user.id,nickname,branch,year,semester}})}catch(e){if(e.code==='23505')return res.status(409).json({error:'That nickname is already taken. Sign in or choose another.'});next(e)}});
app.post('/api/login',rateLimit({name:'login',limit:10,windowMs:15*60_000}),async(req,res,next)=>{try{const key=clean(req.body.nickname,32).toLocaleLowerCase('en-US'),password=req.body.password;if(!key||typeof password!=='string'||password.length>128)return res.status(400).json({error:'Enter your nickname and password.'});const user=await checked(supabase.from('users').select('id,nickname,branch,year,semester,password_hash').eq('nickname_key',key).maybeSingle());if(!user||!await passwordMatches(password,user.password_hash))return res.status(401).json({error:'Nickname or password is incorrect.'});await issueSession(user.id,res);res.json({user:{id:user.id,nickname:user.nickname,branch:user.branch,year:user.year,semester:user.semester}})}catch(e){next(e)}});
app.post('/api/logout',auth,async(req,res,next)=>{try{await checked(supabase.from('sessions').delete().eq('token_hash',hash(req.cookies.session)).eq('user_id',req.user.id));res.setHeader('Set-Cookie',`pp_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0${production?'; Secure':''}`);res.json({ok:true})}catch(e){next(e)}});
app.get('/api/me',optionalAuth,(req,res)=>res.json({user:req.user}));
app.patch('/api/me',auth,async(req,res,next)=>{try{const branch=clean(req.body.branch,60),year=clean(req.body.year,30),semester=clean(req.body.semester,30);if(!branch||!year||!semester)return res.status(400).json({error:'Complete your profile fields.'});await checked(supabase.from('users').update({branch,year,semester}).eq('id',req.user.id));res.json({user:{...req.user,branch,year,semester}})}catch(e){next(e)}});

app.get('/api/state',optionalAuth,async(req,res,next)=>{try{
  const [users,available,materials,ownRequests,ownerItems,notifications]=await Promise.all([
    checked(supabase.from('users').select('id,nickname,branch,year,semester')),
    checked(supabase.from('items').select('id,owner_id,item_name,category,color,quantity,location,description,status,created_at,image_path').in('status',['Available','Requested']).order('created_at',{ascending:false})),
    checked(supabase.from('study_materials').select('id,uploader_id,type,subject,unit,topic,experiment_number,assignment_number,year,semester,branch,description,file_path,created_at').order('created_at',{ascending:false})),
    req.user?checked(supabase.from('requests').select('*').eq('requester_id',req.user.id).order('created_at',{ascending:false})):Promise.resolve([]),
    req.user?checked(supabase.from('items').select('id').eq('owner_id',req.user.id)):Promise.resolve([]),
    req.user?checked(supabase.from('notifications').select('id,user_id,message,read_status,created_at').eq('user_id',req.user.id).order('created_at',{ascending:false}).limit(50)):Promise.resolve([])
  ]);
  const ownIds=ownerItems.map(i=>i.id);let incoming=[];if(ownIds.length)incoming=await checked(supabase.from('requests').select('*').in('item_id',ownIds).order('created_at',{ascending:false}));
  let privateItems=[];if(req.user)privateItems=await checked(supabase.from('items').select('id,owner_id,item_name,category,color,quantity,location,description,status,created_at,image_path').eq('owner_id',req.user.id).in('status',['Given','Unavailable']));
  const items=[...new Map([...available,...privateItems].map(i=>[i.id,i])).values()].map(i=>({id:i.id,owner:i.owner_id,name:i.item_name,category:i.category,color:i.color,quantity:i.quantity,location:i.location,description:i.description,status:i.status,created:i.created_at,image_url:i.image_path?`/api/items/${i.id}/image`:''}));
  const allRequests=[...new Map([...ownRequests,...incoming].map(r=>[r.id,r])).values()].map(r=>({id:r.id,item:r.item_id,requester:r.requester_id,room:r.lecture_theatre,floor:r.floor,block:r.block,place:r.meeting_location,message:r.message,status:r.status,created:r.created_at}));
  res.json({me:req.user,users:users.map(u=>({id:u.id,nickname:u.nickname,branch:u.branch,year:u.year,semester:u.semester})),items,requests:allRequests,materials:materials.map(m=>({id:m.id,owner:m.uploader_id,type:m.type,subject:m.subject,unit:m.unit,topic:m.topic,experiment_number:m.experiment_number,assignment_number:m.assignment_number,year:m.year,semester:m.semester,branch:m.branch,description:m.description,filename:`study-material.${m.file_path.split('.').pop()}`,created:m.created_at,file_url:`/api/materials/${m.id}/file`})),notifications:notifications.map(n=>({id:n.id,message:n.message,read:n.read_status,created:n.created_at}))});
}catch(e){next(e)}});

async function checkedFile(file,kind){if(!file)return {buffer:null,mime:null,ext:null};const {fileTypeFromBuffer}=await import('file-type');const detected=await fileTypeFromBuffer(file.buffer);if(!detected)throw appError('Could not verify the uploaded file format.');const images=['image/jpeg','image/png','image/webp'],docs=['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/x-cfb'];const zipDoc=detected.mime==='application/zip'&&file.buffer.includes(Buffer.from('[Content_Types].xml'))&&file.buffer.includes(Buffer.from('word/'));if(kind==='image'&&(!images.includes(detected.mime)||!images.includes(file.mimetype)))throw appError('Upload a genuine JPEG, PNG, or WebP image.');if(kind==='study'&&!(images.includes(detected.mime)||docs.includes(detected.mime)||zipDoc))throw appError('Upload a genuine PDF, Word document, or JPEG/PNG/WebP image.');const mime=zipDoc?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':detected.mime==='application/x-cfb'?'application/msword':detected.mime;const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','application/pdf':'pdf','application/msword':'doc','application/vnd.openxmlformats-officedocument.wordprocessingml.document':'docx'}[mime];return {buffer:file.buffer,mime,ext}}
const BUCKET_ITEMS='item-images',BUCKET_STUDY='study-materials';
async function storageUpload(bucket,path,file){const {error}=await supabase.storage.from(bucket).upload(path,file.buffer,{contentType:file.mime,upsert:false,cacheControl:'3600'});if(error)throw error;return path}
async function storageDelete(bucket,path){if(path){const {error}=await supabase.storage.from(bucket).remove([path]);if(error)console.error('Storage cleanup failed:',error.message)}}
async function storageDownload(bucket,path){const {data,error}=await supabase.storage.from(bucket).download(path);if(error)throw error;return Buffer.from(await data.arrayBuffer())}
app.post('/api/items',rateLimit({name:'item-upload',limit:20,windowMs:60*60_000}),auth,upload.single('photo'),async(req,res,next)=>{let stored;try{const name=clean(req.body.name,80),category=clean(req.body.category,30),color=clean(req.body.color,20),quantity=Number(req.body.quantity),location=clean(req.body.location,140),description=clean(req.body.description,240);if(name.length<2||!oneOf(category,['Blue Pen','Black Pen','Red Pen','Pencil','Scale','Other'])||!color||!Number.isInteger(quantity)||quantity<1||quantity>99||!location)return res.status(400).json({error:'Check the item details and try again.'});let imagePath=null;if(req.file){if(req.file.size>1_572_864)return res.status(400).json({error:'Item photos must be 1.5 MB or smaller.'});const f=await checkedFile(req.file,'image'),id=crypto.randomUUID();stored=await storageUpload(BUCKET_ITEMS,`${req.user.id}/${id}.${f.ext}`,f);imagePath=stored;await checked(supabase.from('items').insert({id,owner_id:req.user.id,item_name:name,category,color,quantity,location,description,image_path:imagePath,status:'Available'}));return res.status(201).json({id})}const id=crypto.randomUUID();await checked(supabase.from('items').insert({id,owner_id:req.user.id,item_name:name,category,color,quantity,location,description,status:'Available'}));res.status(201).json({id})}catch(e){if(stored)await storageDelete(BUCKET_ITEMS,stored);next(e)}});
app.get('/api/items/:id/image',optionalAuth,async(req,res,next)=>{try{const item=await checked(supabase.from('items').select('owner_id,image_path,status').eq('id',req.params.id).maybeSingle());if(!item?.image_path)return res.sendStatus(404);if(!['Available','Requested'].includes(item.status)&&item.owner_id!==req.user?.id)return res.sendStatus(404);const buf=await storageDownload(BUCKET_ITEMS,item.image_path);const ext=item.image_path.split('.').pop();res.type(({jpg:'image/jpeg',png:'image/png',webp:'image/webp'})[ext]||'application/octet-stream').send(buf)}catch(e){next(e)}});
app.patch('/api/items/:id',auth,async(req,res,next)=>{try{const status=req.body.status;if(!oneOf(status,['Available','Unavailable','Given']))return res.status(400).json({error:'Invalid item status.'});const row=await checked(supabase.from('items').update({status}).eq('id',req.params.id).eq('owner_id',req.user.id).select('id').maybeSingle());if(!row)return res.status(404).json({error:'Item not found or you are not its owner.'});res.json({ok:true})}catch(e){next(e)}});
app.delete('/api/items/:id',auth,async(req,res,next)=>{try{const item=await checked(supabase.from('items').select('id,image_path').eq('id',req.params.id).eq('owner_id',req.user.id).maybeSingle());if(!item)return res.status(404).json({error:'Item not found or you are not its owner.'});await checked(supabase.from('items').delete().eq('id',item.id).eq('owner_id',req.user.id));await storageDelete(BUCKET_ITEMS,item.image_path);res.json({ok:true})}catch(e){next(e)}});
app.post('/api/items/:id/requests',rateLimit({name:'request-create',limit:30,windowMs:60*60_000}),auth,async(req,res,next)=>{try{const item=await checked(supabase.from('items').select('id,owner_id,item_name,status').eq('id',req.params.id).maybeSingle());if(!item||item.status!=='Available')return res.status(404).json({error:'This item is no longer available.'});if(item.owner_id===req.user.id)return res.status(400).json({error:'You cannot request your own item.'});const prior=await checked(supabase.from('requests').select('id').eq('item_id',item.id).eq('requester_id',req.user.id).in('status',['Pending','Accepted']).maybeSingle());if(prior)return res.status(409).json({error:'You already have an active request for this item.'});const id=crypto.randomUUID(),r={id,item_id:item.id,requester_id:req.user.id,lecture_theatre:clean(req.body.room,40),floor:clean(req.body.floor,30),block:clean(req.body.block,30),meeting_location:clean(req.body.place,80),message:clean(req.body.message,240),status:'Pending'};await checked(supabase.from('requests').insert(r));try{await checked(supabase.from('items').update({status:'Requested'}).eq('id',item.id).eq('status','Available'));await createNotification(item.owner_id,`${req.user.nickname} requested your ${item.item_name}.`)}catch(e){await checked(supabase.from('requests').delete().eq('id',id).eq('requester_id',req.user.id));throw e}res.status(201).json({id})}catch(e){if(e.code==='23505')return res.status(409).json({error:'Someone just requested this item. Refresh the page.'});next(e)}});
app.patch('/api/requests/:id',auth,async(req,res,next)=>{try{const status=req.body.status;if(!oneOf(status,['Accepted','Rejected','Given','Cancelled']))return res.status(400).json({error:'Invalid request action.'});const row=await checked(supabase.from('requests').select('id,item_id,requester_id,status,items!inner(owner_id,item_name)').eq('id',req.params.id).maybeSingle());if(!row)return res.status(404).json({error:'Request not found.'});const ownerId=row.items.owner_id,isOwner=ownerId===req.user.id,isRequester=row.requester_id===req.user.id,allowed=isRequester&&status==='Cancelled'&&['Pending','Accepted'].includes(row.status)||isOwner&&['Accepted','Rejected'].includes(status)&&row.status==='Pending'||isOwner&&status==='Given'&&row.status==='Accepted';if(!allowed)return res.status(403).json({error:'That action is not allowed for this request.'});const updated=await checked(supabase.from('requests').update({status}).eq('id',row.id).eq('status',row.status).select('id').maybeSingle());if(!updated)return res.status(409).json({error:'This request changed. Refresh and try again.'});if(['Given','Rejected','Cancelled'].includes(status))await checked(supabase.from('items').update({status:status==='Given'?'Given':'Available'}).eq('id',row.item_id));if(['Accepted','Rejected','Given'].includes(status))await createNotification(row.requester_id,`Your request for ${row.items.item_name} was ${status.toLowerCase()}.`);res.json({ok:true})}catch(e){next(e)}});
app.post('/api/materials',rateLimit({name:'material-upload',limit:10,windowMs:60*60_000}),auth,upload.single('file'),async(req,res,next)=>{let stored;try{const type=clean(req.body.type,40),subject=clean(req.body.subject,100),unit=clean(req.body.unit,80),topic=clean(req.body.topic,120),experiment=type==='Lab Records'?unit:'',assignment=clean(req.body.assignment,50),year=clean(req.body.year,30),semester=clean(req.body.semester,30),branch=clean(req.body.branch,60),description=clean(req.body.description,500);if(!oneOf(type,['Notes','Assignments','Lab Records','Programs/Code','Previous Year Questions','Study Material'])||!subject||!semester||!branch||!req.file)return res.status(400).json({error:'Complete the required fields and choose a study file.'});const f=await checkedFile(req.file,'study'),id=crypto.randomUUID();stored=await storageUpload(BUCKET_STUDY,`${req.user.id}/${id}.${f.ext}`,f);await checked(supabase.from('study_materials').insert({id,uploader_id:req.user.id,type,subject,unit,topic,experiment_number:experiment,assignment_number:assignment,year,semester,branch,description,file_path:stored}));res.status(201).json({id})}catch(e){if(stored)await storageDelete(BUCKET_STUDY,stored);next(e)}});
app.get('/api/materials/:id/file',auth,async(req,res,next)=>{try{const m=await checked(supabase.from('study_materials').select('file_path,subject').eq('id',req.params.id).maybeSingle());if(!m)return res.sendStatus(404);const data=await storageDownload(BUCKET_STUDY,m.file_path);const ext=m.file_path.split('.').pop(),mime={pdf:'application/pdf',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',jpg:'image/jpeg',png:'image/png',webp:'image/webp'}[ext]||'application/octet-stream';res.set('Content-Type',mime).set('Content-Disposition',`attachment; filename="study-material.${ext}"`).send(data)}catch(e){next(e)}});
app.delete('/api/materials/:id',auth,async(req,res,next)=>{try{const m=await checked(supabase.from('study_materials').select('id,file_path').eq('id',req.params.id).eq('uploader_id',req.user.id).maybeSingle());if(!m)return res.status(404).json({error:'Study material not found or you are not its uploader.'});await checked(supabase.from('study_materials').delete().eq('id',m.id).eq('uploader_id',req.user.id));await storageDelete(BUCKET_STUDY,m.file_path);res.json({ok:true})}catch(e){next(e)}});

app.get('/health',(_req,res)=>res.sendStatus(200));
app.get(['/', '/index.html'],(_req,res)=>res.sendFile(require('node:path').join(__dirname,'public','index.html')));
app.get('/client.js',(_req,res)=>res.type('application/javascript').sendFile(require('node:path').join(__dirname,'public','client.js')));
app.use('/api',(req,res)=>res.status(404).json({error:'API route not found.'}));
app.use((_req,res)=>res.sendStatus(404));
app.use((err,_req,res,_next)=>{console.error(err.message);let status=err.status||(err instanceof multer.MulterError?400:500);if(err.code==='23505')status=409;res.status(status).json({error:status===500?'Something went wrong. Please try again.':err.message})});

if(require.main===module){ready().then(()=>{const server=app.listen(PORT,production?'0.0.0.0':'127.0.0.1',()=>console.log(`PenPals Campus listening on http://127.0.0.1:${PORT}`));for(const sig of ['SIGINT','SIGTERM'])process.on(sig,()=>server.close(()=>process.exit(0)))}).catch(e=>{console.error('Startup failed:',e.message);process.exit(1)})}
module.exports={app,ready};
